[project]
name = "hello-mcp"
version = "0.1.0"
description = "Hello MCP project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.2",
    "httpx>=0.28.1",
]

[project.scripts]
run-server = "main:main"
