[project]
name = "hello-mcp"
version = "0.1.0"
description = "Hello MCP project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.21.2",
]

[project.scripts]
run-server = "main:main"
